### ISSUE TITLE
Enhance "datalayers switcher"

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#1135]
Here is how it looks currently:

![image](https://github.com/umap-project/umap/assets/146023/600d888d-0121-4bf5-8565-b9c4ce921998)

A few feedback:

- it should include colors and icons of each datalayer
- it should be in the bottom of the screen, to be less intrusive (maybe merge with new "permanent credit")
-

**Comment by yohanboniface** [comment]
A few more questions/remarks:

- should the users be able to chose the position (top/bottom left/right) ?
- should we include caption text when provided ? Otherwise, we may need to work on a "small caption box", because the current one in the full panel is quite intrusive
- I'm in the process to allow choosing which layers would go in this box: some layer be only be for esthetics reasons, or be unfinished…
- should we allow to display some features in the legend ? either because they represent some sort of features one may want to showcase ("those features are the hospitals"), either because as a feature it should be show cased ("this feature is the finish of the race")

**Comment by almet** [comment]
See #1469

**Comment by yohanboniface** [comment]
Done in #1687 and following PRs

**Comment by entrider** [comment]
> should the users be able to chose the position (top/bottom left/right) ?

It would be great! I still can't get used to it being on the left.
