### ISSUE TITLE
Data Loss During Save

### ISSUE THREAD

**Issue by timoto** [umap-project/umap#418]
I was extending a polyline at umap, that I've been updating for years, but when I hit save the line disappeared.
https://umap.openstreetmap.fr/en/user/globaltimoto/

Is there an undo ? How can I go back ?

Is the data lost forever? It was so much work.

**Comment by yohanboniface** [comment]
Which map?
Are you working behind a proxy?
Have you tried loading the map from another browser/computer/network? It may be a cache issue.

You can try restoring previous version of the layer: edit the layer, and look at the bottom of the panel to see the list of available versions.

**Comment by timoto** [comment]
Hi Yohan

Thanks for the fast feedback.

Phew, I didn't know about the versioning being available. That helped!

Strangely though the dates do not appear to be correct in the versioning.

I was able to retrieve what I needed here:
13 June 48912 05:10:57 (131.935Kb)

Then when I made another save and looked back at the latest version just now:
12 July 48912 15:04:05 (129.442Kb)

Odd no ?

**Comment by yohanboniface** [comment]
> Odd no ?

Ah ah, fun, I'll look at this asap :)

**Comment by yohanboniface** [comment]
Fixed the date issue, will be live with next release.
Closing here, as it seems no further action is needed.

**Comment by datendelphin** [comment]
This fix is still missing in the latest (tagged) umap version 0.8.0-rc13 I'm not sure if I should switch to master to get bugfixes, if it is stable enough.

**Comment by yohanboniface** [comment]
My bad, forgot to push some tags. You should now find 0.8.0, 0.8.1, 0.8.2.

**Comment by datendelphin** [comment]
Thank you :)

**Comment by timoto** [comment]
Regression ?

Not sure why my route data keeps getting trashed when I hit save, but now when I attempt to retrieve a previous version, nothing is listed, help !!!

![image](https://user-images.githubusercontent.com/1268358/29263144-ca64f64a-8116-11e7-98cc-1a0f740a099a.png)

**Comment by timoto** [comment]
Regression ?

Not sure why my route data keeps getting trashed when I hit save, but now when I attempt to retrieve a previous version, nothing is listed, help !!!

![image](https://user-images.githubusercontent.com/1268358/29263346-849a6806-8117-11e7-8175-7c4665e5d340.png)
