### ISSUE TITLE
Wrong username display with OSM login 

### ISSUE THREAD

**Issue by bagage** [umap-project/umap#962]
When connecting with an OSM account, uMap displays the initial/original name from OSM account, even if you renamed yourself on OSM. Would be nice to use the latest name instead.

**Comment by yohanboniface** [comment]
Should have been fixed by https://github.com/umap-project/umap/pull/754
Can you give more details ?

cc @Binnette

**Comment by bagage** [comment]
Well, not sure what kind of details but basically:

- my OSM account is now [`bagage`](https://www.openstreetmap.org/user/bagage), 
- but on Umap my old name is used [`GautierPP`](https://umap.openstreetmap.fr/fr/user/GautierPP/)
- I logged to UMap with OSM auth in.

Is there anything else I can provide which could be relevant?

**Comment by mdino-gh** [comment]
I can confirm that the issue is still present. I just changed my OSM display name from kuddel12 to mdino. But in uMap still kuddel 12 ist shown, when i log in with my OSM account.

Things I have done so far:

- logged of and back in into uMap with my OSM account
- checked it on an incognito tab from the browser to make sure that the issue is not coming from cookies stored in browser
- used Chrome instead of Firefox
- removed all maps from uMap that I have created under old username
- removed all OAuth 1 umap applications from OSM account (anyways every time I am logging into uMap a new OAuth1 application is created in OSM)

**Comment by HDValentin** [comment]
I have the same issue.
Synchronizing the Username with openstreetmap.org on login would solve this issue.

**Comment by yohanboniface** [comment]
Could you try again ?

**Comment by HDValentin** [comment]
@yohanboniface works for me. The Name is correct synchronized in Profile and the maps after login. Thank you!

**Comment by mdino-gh** [comment]
Yes, it works for me as well. Thank you!

**Comment by yohanboniface** [comment]
Thanks for confirm!
